name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Bun
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps and build (with cache)
        run: bun install

      - name: Test
        run: bun test --ci --coverage

      - name: Build
        run: bun run build
